### ISSUE TITLE
FSK Decoding candidate

### ISSUE THREAD

**Issue by janvgils** [kng/satnogs_gr-satellites#2]
Now with the development trying to add FSK support I would suggest to add AAUSAT-4.
There doesn't seem to be a decoder within SatNOGS so lets try to activate the gr_satellites decoder for AAUSAT-4

`gr_satellites --list_satellites`

```
* AAUSAT-4 (NORAD 41460)
    2k4 FSK downlink 437.425 MHz FSK AAUSAT-4
    9k6 FSK downlink 437.425 MHz FSK AAUSAT-4

```

**Comment by kng** [comment]
It may already be working, this is from earlier today on my station, it uses the satnogs_fsk.py as well as the bpsk.
https://network.satnogs.org/observations/3234089/

**Comment by kng** [comment]
the FSK flowgraph seems to be working, I am working on getting all added to the satnogs-flowgraphs.
The data I get is not the same as OZ3RF, also except two header and two footer bytes. This is another discussion and outside this scope. Refering to this: https://community.libre.space/t/standardization-of-frames-formats-for-satnogs-db/7057/1

https://network.satnogs.org/observations/3287088/
https://network.satnogs.org/observations/3287095/
