### ISSUE TITLE
Updating SATLIST

### ISSUE THREAD

**Issue by janvgils** [kng/satnogs_gr-satellites#4]

**Comment by janvgils** [comment]
If I am correct is the variable `$SATLIST` responsible for the function to see if `gr_satellites` can decode a SatNOGS observation.

After I updated `gr_satellites` the `grsat-wrapper.sh` was still not decoding observation that where supported with the new `gr_satellites` build, I this example CAPE-3.

Would it be an idea to check if `gr_satellites` is changed to regenerate the `$SATLIST` list?

Maybe something like:

`date -r /usr/local/bin/gr_satellites` or `stat -c %z /usr/local/bin/gr_satellites`

**Comment by kng** [comment]
Agreed on this feature. Just pushed a solution for it based on your suggestions. Let's see if it runs ok.

**Comment by janvgils** [comment]
Thanks for the update and testing, what is the best way to update this change?
Just replace the `grsat-wrapper.sh` wrapper?

**Comment by kng** [comment]
That will work, make note of the settings you've made. KEEPLOGS, IQMODE, SELECTED.

**Comment by janvgils** [comment]
This upgrade is working and therefor the issue can be closed.
