### ISSUE TITLE
Cache of supported satellites might be empty

### ISSUE THREAD

**Issue by kng** [kng/satnogs_gr-satellites#8]
Check if the file size is 0, this could mean a previous run had some problems and produced a empty list of satellites.

**Comment by janvgils** [comment]
Where can this cache be found?

**Comment by kng** [comment]
https://github.com/kng/satnogs_gr-satellites/blob/main/grsat-wrapper.sh#L15
If that file is 0 size, it indicates that gr_satellites did the "cannot find module named: satellites" or other crash, resulting in a empty list. It can be tested for zero size at line 49
